[inkcutBox]
image=docker.io/library/alpine:3.22
home=/home/${USER}/distrobox/inkcutBox
pull=false
start_now=true
additional_packages="gcc cups-dev musl-dev linux-headers"
additional_packages="python3-dev pipx py3-pip py3-qt6"
additional_packages="fastfetch git"
# Build/Install inkcut
init_hooks=pipx install git+https://github.com/codelv/inkcut.git;
# link system PyQt directory to prevent
# qtpy.QtBindingsNotFoundError: No Qt bindings could be found
init_hooks=ln -s /usr/lib/python3.12/site-packages/PyQt6 ~/.local/share/pipx/venvs/inkcut/lib/python3.12/site-packages/;
exported_bins="/home/${USER}/distrobox/inkcutBox/.local/bin/inkcut"
exported_bins_path="/home/${USER}/.local/bin"
